# Generated by Django 3.0.3 on 2020-02-24 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('terms_of_service_agreements', '0004_auto_20200223_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, help_text='uuid: Unique user identifier'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='document',
            field=models.ForeignKey(help_text='valid terms endpoint schema json object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='terms_of_service_agreements.TermsOfService'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='user',
            field=models.ForeignKey(help_text='valid user schema endpoint json object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='terms_of_service_agreements.UserData'),
        ),
    ]
