# Generated by Django 3.0.3 on 2020-02-18 16:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import terms_of_service_agreements.models


class Migration(migrations.Migration):

    dependencies = [
        ('terms_of_service_agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofservice',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[terms_of_service_agreements.models.validate_terms_of_service_content]),
        ),
    ]
